# Generated by Django 5.0 on 2024-01-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='office_floors',
            field=models.ManyToManyField(blank=True, null=True, to='staff_module.floor', verbose_name='Office Floors'),
        ),
    ]
