# Generated by Django 5.0.1 on 2024-01-07 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_module', '0002_alter_customuser_office_floors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='team',
        ),
        migrations.AddField(
            model_name='projects',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Project Managers'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='staff_module.projects', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='team_lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Team Lead'),
        ),
    ]
